### ISSUE TITLE
搜索引擎問答 - API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by LeoHsu0802** [chatchat-space/Langchain-Chatchat#2980]
**问题描述 / Problem Description**

使用duckduckgo搜索引擎回答詢問問題時出現  API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/opt/conda/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/opt/conda/lib/python3.10/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
    await self.message_event.wait()
  File "/opt/conda/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f11643af220

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/conda/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/opt/conda/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/ubuntu/Langchain-Chatchat/server/chat/search_engine_chat.py", line 164, in search_engine_chat_iterator
    |     docs = await lookup_search_engine(query, search_engine_name, top_k, split_result=split_result)
    |   File "/home/ubuntu/Langchain-Chatchat/server/chat/search_engine_chat.py", line 112, in lookup_search_engine
    |     results = await run_in_threadpool(search_engine, query, result_len=top_k, split_result=split_result)
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |   File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    |     return await future
    |   File "/opt/conda/lib/python3.10/asyncio/futures.py", line 285, in __await__
    |     yield self  # This tells Task to wait for completion.
    |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |   File "/home/ubuntu/Langchain-Chatchat/server/chat/search_engine_chat.py", line 36, in duckduckgo_search
    |     search = DuckDuckGoSearchAPIWrapper()
    |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    | pydantic.error_wrappers.ValidationError: 1 validation error for DuckDuckGoSearchAPIWrapper
    | __root__
    |   Can't patch loop of type <class 'uvloop.Loop'> (type=value_error)
    +------------------------------------
2024-02-15 08:12:16,760 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.1
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：duckduckgo - 索引擎回答
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：duckduckgo - 索引擎回答
- 操作系统及版本 / Operating system and version: Ubuntu 20.4
- Python 版本 / Python version:  3.10.9
- 其他相关环境信息 / Other relevant environment information:
AWS g5.sxlarge
Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.1.0 (Ubuntu 20.04)

**Comment by zRzRzRzRzRzRzR** [comment]
填写key了吗

**Comment by LeoHsu0802** [comment]
@zRzRzRzRzRzRzR 請問您指的KEY是? 我以為duckduckgo不需要額外的key

**Comment by zRzRzRzRzRzRzR** [comment]
如果是duckduckgo就需要外网环境，国内用不了

**Comment by LeoHsu0802** [comment]
@zRzRzRzRzRzRzR , 但我是在國外環境測試的，我在用openai-api時有遇到相同錯誤，已在model config內加入 open ai api key

**Comment by Macbook-Specter** [comment]
感觉@zRzRzRzRzRzRzR 就是应付了事，问题没解决就关闭了，看了很多都是

**Comment by ZhichaoOuyang** [comment]
> 嗐，不知道您有没有解决这个问题？因为是本地部署，搜索引擎需要挂梯子，我在程序外直接调用重载后的函数是可以顺利运行的，在项目里调用就总报异步函数的错误。 ERROR: Exception in ASGI application Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi result = await app( # type: ignore[func-returns-value] File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__ return await self.app(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__ await super().__call__(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__ await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__ raise exc File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__ await self.app(scope, receive, _send) File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__ raise exc File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__ raise e File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 270, in __call__ async with anyio.create_task_group() as task_group: File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__ raise exceptions[0] File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 273, in wrap await func() File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 262, in stream_response async for chunk in self.body_iterator: File "/chatchat/LangchainChatchatdev022v3/server/chat/search_engine_chat.py", line 116, in search_engine_chat_iterator docs = await lookup_search_engine(query, search_engine_name, top_k) File "/chatchat/LangchainChatchatdev022v3/server/chat/search_engine_chat.py", line 74, in lookup_search_engine results = await run_in_threadpool(search_engine, query, result_len=top_k) File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool return await anyio.to_thread.run_sync(func, *args) File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) File "/chatchat/LangchainChatchatdev022v3/server/chat/search_engine_chat.py", line 35, in duckduckgo_search search = DuckDuckGoSearchAPIWrapper() File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for DuckDuckGoSearchAPIWrapper __root__ Can't patch loop of type <class 'uvloop.Loop'&gt; (type=value_error) 血落尘埃 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chatchat-space/Langchain-Chatchat" ***@***.***&gt;; 发送时间:&nbsp;2024年2月26日(星期一) 下午2:34 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] 搜索引擎問答 - API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read) (Issue #2980) ***@***.*** 就是应付了事，问题没解决就关闭了，看了很多都是 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

和你一样的问题 请问如何解决

**Comment by saltedfish2** [comment]
duckduckgo我没办法了，参考2.10版本的处理重新更改了调用方式也不行。申请了bing的key，有免费额度，比较麻烦的是需要绑信用卡。




血落尘埃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月29日(星期四) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] 搜索引擎問答 - API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read) (Issue #2980)





  
嗐，不知道您有没有解决这个问题？因为是本地部署，搜索引擎需要挂梯子，我在程序外直接调用重载后的函数是可以顺利运行的，在项目里调用就总报异步函数的错误。 ERROR: Exception in ASGI application Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi result = await app( # type: ignore[func-returns-value] File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in call return await self.app(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in call await super().call(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in call await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in call raise exc File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in call await self.app(scope, receive, _send) File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in call raise exc File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in call await self.app(scope, receive, sender) File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in call raise e File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in call await self.app(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in call await route.handle(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 270, in call async with anyio.create_task_group() as task_group: File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in aexit raise exceptions[0] File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 273, in wrap await func() File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 262, in stream_response async for chunk in self.body_iterator: File "/chatchat/LangchainChatchatdev022v3/server/chat/search_engine_chat.py", line 116, in search_engine_chat_iterator docs = await lookup_search_engine(query, search_engine_name, top_k) File "/chatchat/LangchainChatchatdev022v3/server/chat/search_engine_chat.py", line 74, in lookup_search_engine results = await run_in_threadpool(search_engine, query, result_len=top_k) File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool return await anyio.to_thread.run_sync(func, args) File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, args) File "/chatchat/LangchainChatchatdev022v3/server/chat/search_engine_chat.py", line 35, in duckduckgo_search search = DuckDuckGoSearchAPIWrapper() File "pydantic/main.py", line 341, in pydantic.main.BaseModel.init pydantic.error_wrappers.ValidationError: 1 validation error for DuckDuckGoSearchAPIWrapper root Can't patch loop of type <class 'uvloop.Loop'&gt; (type=value_error) 血落尘埃 @.* &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chatchat-space/Langchain-Chatchat" @.&gt;; 发送时间:&nbsp;2024年2月26日(星期一) 下午2:34 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] 搜索引擎問答 - API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read) (Issue #2980) @.*** 就是应付了事，问题没解决就关闭了，看了很多都是 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
和你一样的问题 请问如何解决

**Comment by zhousteven** [comment]
确实是需要梯子才能访问的，我是直接将安装包里的代码拿出来，然后加了代理IP之后，就能访问，也可以设置系统级设置
