### ISSUE TITLE
在初始化过程中，显存爆了

### ISSUE THREAD

**Issue by loki-keroro** [chatchat-space/Langchain-Chatchat#4101]
更换了更大一点的向量化模型bge-m3，在初始化比较大文件的时候会爆显存，导致无法继续进行初始化，请问有什么办法分批或者量化模型的方式来解决？
报错内容：
”CUDA out of memory. Tried to allocate 128.00 GiB. GPU 0 has a total capacty of 23.69 GiB of which 14.50 GiB is free. Process 356231 has 9.18 GiB memory in use. Of the allocated memory 8.13 GiB is allocated by PyTorch, and 8.94 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception in thread Thread-1:“
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58797741/3abc465b-f9a9-4c29-aa9e-3d9cafab6d93)

**Comment by HugoShaw** [comment]
> 更换了更大一点的向量化模型bge-m3，在初始化比较大文件的时候会爆显存，导致无法继续进行初始化，请问有什么办法分批或者量化模型的方式来解决？ 报错内容： ”CUDA out of memory. Tried to allocate 128.00 GiB. GPU 0 has a total capacty of 23.69 GiB of which 14.50 GiB is free. Process 356231 has 9.18 GiB memory in use. Of the allocated memory 8.13 GiB is allocated by PyTorch, and 8.94 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF Exception in thread Thread-1:“ ![image](https://private-user-images.githubusercontent.com/58797741/334625073-3abc465b-f9a9-4c29-aa9e-3d9cafab6d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjYyNTMsIm5iZiI6MTcxNjk2NTk1MywicGF0aCI6Ii81ODc5Nzc0MS8zMzQ2MjUwNzMtM2FiYzQ2NWItZjlhOS00YzI5LWFhOWUtM2Q5Y2FmYWI2ZDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MWRiZGY1OTdmZWNkMTQ5OTM1MGYyN2FiODVjYzMxMDI3YWM0NDBmNTQ4YmIwNTUzNGQ1ZGViOWI1NzMzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WPnmzuP-T_gDqKOdf43tT7pJr_dA62vuTbXhDKKTTdI)

I encounter same problem, and follow the prompt to set PYTORCH_CUDA_ALLOC_CONF=>setting max_split_size_mb:128, but still fail to solve the problem:
**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(CUDA out of memory. Tried to allocate 22.00 MiB. GPU 1 has a total capacty of 16.00 GiB of which 0 bytes is free. Of the allocated memory 15.11 GiB is allocated by PyTorch, and 102.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
