### ISSUE TITLE
bash: chatchat-config: command not found

### ISSUE THREAD

**Issue by hahalaughddd** [chatchat-space/Langchain-Chatchat#4515]
按照pip install langchain-chatchat -U、pip install "langchain-chatchat[xinference]" -U
后使用chatchat-config --help报错
bash: chatchat-config: command not found

**Comment by yellow123Nike** [comment]
这是什么问题

**Comment by sevenandseven** [comment]
> chatchat-config

你好，我出现了同样的问题，请问怎么解决？

**Comment by yellow123Nike** [comment]
直接chatchat init

**Comment by sevenandseven** [comment]
> 直接chatchat init

没有用，还是不存在，而且初始化向量库的时候也会报错： ERROR    | chatchat.server.knowledge_base.kb_cache.faiss_cache:load_vector_store:140 - Error raised by inference endpoint: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff603051060>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-25 14:57:17.549 | ERROR    | chatchat.init_database:worker:61 - 向量库 samples 加载失败。

**Comment by liming51** [comment]
有人解决了吗？如何解决的

**Comment by TwinkleYR** [comment]
> > 直接chatchat init
> 
> 没有用，还是不存在，而且初始化向量库的时候也会报错： ERROR | chatchat.server.knowledge_base.kb_cache.faiss_cache:load_vector_store:140 - Error raised by inference endpoint: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff603051060>: Failed to establish a new connection: [Errno 111] Connection refused')) 2024-07-25 14:57:17.549 | ERROR | chatchat.init_database:worker:61 - 向量库 samples 加载失败。
the same question

**Comment by FirmamentWu** [comment]
> > 直接chatchat init
> 
> 没有用，还是不存在，而且初始化向量库的时候也会报错： ERROR | chatchat.server.knowledge_base.kb_cache.faiss_cache:load_vector_store:140 - Error raised by inference endpoint: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff603051060>: Failed to establish a new connection: [Errno 111] Connection refused')) 2024-07-25 14:57:17.549 | ERROR | chatchat.init_database:worker:61 - 向量库 samples 加载失败。

这个找到解决方案了么？
