### ISSUE TITLE
请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？

### ISSUE THREAD

**Issue by PeiwenWu** [chatchat-space/Langchain-Chatchat#4688]

**Comment by liunux4odoo** [comment]
请参阅 readme

**Comment by Nancy7zt** [comment]
你说的是3.0 还是2.10  3.0肯定支持

**Comment by PeiwenWu** [comment]
2.10呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月8日(周四) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688)




 
你说的是3.0 还是2.10  3.0肯定支持

**Comment by Nancy7zt** [comment]
目前我是这样解决的，你用mindie 把大模型服务起起来，然后也把embedding 起了。把那个模型接入写openai-api  目前我只跑通了大模型对话的那个接口，知识库的接口一直报错，似乎不支持多并发的api

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月08日 18:22 |
| 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> |
| 抄送人 | leozz77 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) |

2.10呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月8日(周四) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688)





你说的是3.0 还是2.10 3.0肯定支持

**Comment by pengshuang29** [comment]
请问embedding通过什么启动？可以使用xinference吗？

> 目前我是这样解决的，你用mindie 把大模型服务起起来，然后也把embedding 起了。把那个模型接入写openai-api 目前我只跑通了大模型对话的那个接口，知识库的接口一直报错，似乎不支持多并发的api
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年08月08日 18:22 | | 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> | | 抄送人 | leozz77 ***@***.***>, Comment ***@***.***> | | 主题 | Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) | 2.10呢
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月8日(周四) 下午5:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) 你说的是3.0 还是2.10 3.0肯定支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Nancy7zt** [comment]
Embedding 用fastchat 启动的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月21日 06:46 |
| 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> |
| 抄送人 | leozz77 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) |

请问embedding通过什么启动？可以使用xinference吗？

目前我是这样解决的，你用mindie 把大模型服务起起来，然后也把embedding 起了。把那个模型接入写openai-api 目前我只跑通了大模型对话的那个接口，知识库的接口一直报错，似乎不支持多并发的api
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年08月08日 18:22 | | 收件人 | chatchat-space/Langchain-Chatchat @.> | | 抄送人 | leozz77 @.>, Comment @.> | | 主题 | Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) | 2.10呢
---原始邮件--- 发件人: @.> 发送时间: 2024年8月8日(周四) 下午5:57 收件人: @.>; 抄送: @.@.>; 主题: Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) 你说的是3.0 还是2.10 3.0肯定支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

**Comment by ArronAI007** [comment]
> Embedding 用fastchat 启动的
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年09月21日 06:46 | | 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> | | 抄送人 | leozz77 ***@***.***>, Comment ***@***.***> | | 主题 | Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) | 请问embedding通过什么启动？可以使用xinference吗？ 目前我是这样解决的，你用mindie 把大模型服务起起来，然后也把embedding 起了。把那个模型接入写openai-api 目前我只跑通了大模型对话的那个接口，知识库的接口一直报错，似乎不支持多并发的api … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年08月08日 18:22 | | 收件人 | chatchat-space/Langchain-Chatchat @.> | | 抄送人 | leozz77 @.>, Comment @.> | | 主题 | Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) | 2.10呢 ---原始邮件--- 发件人: @.> 发送时间: 2024年8月8日(周四) 下午5:57 收件人: @.>; 抄送: @.@.>; 主题: Re: [chatchat-space/Langchain-Chatchat] 请问langchain-Chatchat框架是否适配昇腾？和昇腾的哪些机型适配呢？ (Issue #4688) 你说的是3.0 还是2.10 3.0肯定支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

fastchat和ollama哪个更快一些呢？
